n = int(input("Enter number of elements: "))
a = list(map(int, input("Enter elements: ").split()))
t = tuple(a)
print("Original list:", a)
print("Largest:", max(a))
print("Smallest:", min(a))
print("Sum:", sum(a))
print("Average:", sum(a) / n)
print("Even:", sum(x % 2 == 0 for x in a))
print("Odd:", sum(x % 2 != 0 for x in a))
print("Ascending:", sorted(a))
print("Descending:", sorted(a, reverse=True))
a = list(dict.fromkeys(a))
print("Without duplicates:", a)
print("Final tuple:", tuple(a))
